# Generated by Django 4.0.4 on 2022-04-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_production',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_sales',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('sales', 'sales'), ('production', 'production')], default='admin', max_length=10),
        ),
    ]
