# Generated by Django 4.0.4 on 2022-04-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_admin_remove_user_is_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('sales', 'sales'), ('production', 'production')], max_length=10),
        ),
    ]
